// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"testdemo/internal/biz"
	"testdemo/internal/conf"
	"testdemo/internal/data"
	"testdemo/internal/server"
	"testdemo/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(dataData)
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	greeterService := service.NewGreeterService()
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase)
	grpcServer := server.NewGRPCServer(confServer, todoService, greeterService, userService)
	meterProvider := server.NewMeterProvider()
	httpServer := server.NewHTTPServer(confServer, meterProvider, todoService, greeterService, userService)
	consulRegistry := server.NewRegistry(registry)
	registrar := server.NewRegistrar(consulRegistry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
